---
name: "Linting"
on:  # yamllint disable-line rule:truthy
  push:
    branches:
      - "*"
jobs:
  linting:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: lint
        uses: ghe-actions/dockerfile-validator@v1
        with:
          dockerfile: 'Dockerfile'
          lint: 'hadolint'